name: Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: hdlc/verible
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          LINT_RULES="-always-ff-non-blocking,parameter-name-style=localparam_style:ALL_CAPS,-interface-name-style,-generate-label-prefix"
          verible-verilog-lint -rules=$LINT_RULES $(find src/ -type f | grep .sv)
          verible-verilog-lint -rules=$LINT_RULES $(find tb/ -type f | grep .sv)