name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: hdlc/verilator
    steps:
      - name: Run apt update
        run: apt update 2>/dev/null
      - name: Run apt install prerequisites
        run: |
          # apt install -y clang-9
          # ln -s /usr/bin/clang++-9 /usr/bin/clang++
          apt install -y cmake ninja-build
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd test
          cmake -S . -B build -G Ninja
          ninja -C build
      - name: Run tests
        run: |
          cd test
          ./build/test_all
